import type { NextPage } from 'next'
import Head from 'next/head'
import BookingPanel from '../components/BookingPanel'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import Map from '../components/Map'
import Marquee from '../components/Marquee'
import Passes from '../components/Passes'
import Resorts from '../components/Resorts'
import Slides from '../components/Slides'


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <BookingPanel />
      <Marquee />
      <Map />
      <Slides />
      <Resorts />
      <Passes />
      <Footer />
    </>
  )
}

export default Home
