import type { NextPage } from 'next'
import Head from 'next/head'
import BookingPanel from '../components/BookingPanel'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import Map from '../components/Map'
import Marquee from '../components/Marquee'
import Passes from '../components/Passes'
import Resorts from '../components/Resorts'
import Slides from '../components/Slides'
import { motion } from 'framer-motion'
import { variants } from '../utils/data';




const Home: NextPage = () => {

   return (
    <motion.main
      variants={variants}
      initial="hidden" 
      animate="enter"  
      exit="exit" 
      transition={{ type: 'linear' }} 
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <BookingPanel />
      <Marquee />
      <Map />
      <Slides />
      <Resorts />
      <Passes />
      <Footer />
    </motion.main>
    
  )
}

export default Home
